# Copyright 2025 - Oumi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Helper script template that gets written into AIDE's workspace.

The AIDE agent's generated code imports from this helper, which handles
all Oumi API boilerplate. This ensures generated scripts work regardless
of model, trainer type, or Oumi version.
"""

# This is the content of the oumi_helper.py file that gets written
# into the AIDE workspace directory. The agent's generated code
# imports and calls these functions.
OUMI_HELPER_SCRIPT = '''\
"""Oumi helper functions for AIDE-generated scripts.

This file is auto-generated by Oumi's AIDE integration.
Use these functions instead of calling Oumi's API directly.
"""

import os
import sys
import dataclasses

# Disable rich logging (incompatible with AIDE's subprocess stdout redirect).
os.environ["OUMI_DISABLE_RICH_LOGGING"] = "true"


def run_trial(
    base_config_path: str,
    overrides: dict | None = None,
    target_metric: str = "eval_loss",
) -> float:
    """Train a model and return the target metric.

    Loads the base config from YAML, applies overrides, trains, and
    extracts the metric. Handles all Oumi boilerplate.

    Args:
        base_config_path: Path to an Oumi training config YAML.
        overrides: Dict of dot-notation field paths to values, e.g.
            {"training.learning_rate": 1e-4, "training.optimizer": "adafactor"}
        target_metric: Name of the metric to extract from training results.

    Returns:
        The metric value as a float.
    """
    import os
    from oumi.core.configs import TrainingConfig
    from oumi.train import train

    # Resolve config path: check current dir first, then as-is.
    if not os.path.exists(base_config_path):
        local = os.path.basename(base_config_path)
        if os.path.exists(local):
            base_config_path = local

    try:
        config = TrainingConfig.from_yaml(base_config_path)
    except Exception as e:
        raise ValueError(
            f"Failed to load training config from '{base_config_path}': {e}"
        ) from e

    # Apply overrides via dot-notation.
    if overrides:
        for key, value in overrides.items():
            parts = key.split(".")
            obj = config
            for part in parts[:-1]:
                obj = getattr(obj, part)
            setattr(obj, parts[-1], value)

    # Ensure output goes to working directory.
    if not config.training.output_dir.startswith("./working"):
        config.training.output_dir = "./working/trial_output"

    # Disable wandb in AIDE subprocess.
    config.training.enable_wandb = False

    # Train and extract metric.
    eval_results = train(config)

    if eval_results and target_metric in eval_results:
        metric = float(eval_results[target_metric])
        print(f"{target_metric}={metric}")
        return metric

    raise ValueError(
        f"Metric \\'{target_metric}\\' not found in results: {eval_results}"
    )


def test_reward(
    reward_fn,
    base_config_path: str,
    target_metric: str = "eval_loss",
    max_steps: int = 50,
) -> float:
    """Test a reward function by running a short GRPO training.

    Args:
        reward_fn: A callable with signature
            (completions: list[str], prompts: list[str] | None, **kwargs)
            -> list[float]
        base_config_path: Path to a GRPO training config YAML.
        target_metric: Metric to extract.
        max_steps: Number of training steps.

    Returns:
        The metric value as a float.
    """
    import os
    from oumi.core.configs import TrainingConfig
    from oumi.core.registry import REGISTRY, RegistryType
    from oumi.train import train

    if not os.path.exists(base_config_path):
        local = os.path.basename(base_config_path)
        if os.path.exists(local):
            base_config_path = local

    try:
        config = TrainingConfig.from_yaml(base_config_path)
    except Exception as e:
        raise ValueError(
            f"Failed to load config from '{base_config_path}': {e}"
        ) from e

    # Register the reward function.
    reward_name = "_aide_test_reward"
    REGISTRY.register(
        name=reward_name, type=RegistryType.REWARD_FUNCTION, value=reward_fn
    )

    config.training.reward_functions = [reward_name]
    config.training.max_steps = max_steps
    config.training.output_dir = "./working/reward_trial"
    config.training.enable_wandb = False

    eval_results = train(config)

    if eval_results and target_metric in eval_results:
        metric = float(eval_results[target_metric])
        print(f"{target_metric}={metric}")
        return metric

    raise ValueError(
        f"Metric \\'{target_metric}\\' not found in results: {eval_results}"
    )


def test_eval(
    eval_fn,
    base_config_path: str,
    target_metric: str = "accuracy",
) -> float:
    """Test a custom evaluation function.

    Args:
        eval_fn: A callable that takes (task_params, config, inference_engine)
            and returns a dict of metric names to values.
        base_config_path: Path to an Oumi evaluation config YAML.
        target_metric: Metric to extract from eval_fn's return dict.

    Returns:
        The metric value as a float.
    """
    import os
    from oumi.core.configs import EvaluationConfig
    from oumi.core.evaluation import Evaluator
    from oumi.core.registry import REGISTRY, RegistryType

    if not os.path.exists(base_config_path):
        local = os.path.basename(base_config_path)
        if os.path.exists(local):
            base_config_path = local

    try:
        config = EvaluationConfig.from_yaml(base_config_path)
    except Exception as e:
        raise ValueError(
            f"Failed to load eval config from '{base_config_path}': {e}"
        ) from e

    # Register the evaluation function.
    eval_name = "_aide_test_eval"
    REGISTRY.register(
        name=eval_name, type=RegistryType.EVALUATION_FUNCTION, value=eval_fn
    )

    config.tasks[0].task_name = eval_name
    config.tasks[0].evaluation_backend = "custom"

    evaluator = Evaluator()
    results = evaluator.evaluate(config)

    for result in results:
        result_dict = result.get_results()
        if target_metric in result_dict:
            metric = float(result_dict[target_metric])
            print(f"{target_metric}={metric}")
            return metric

    raise ValueError(
        f"Metric \\'{target_metric}\\' not found in eval results"
    )


def get_config_fields(base_config_path: str) -> dict:
    """Return all modifiable training config fields and their current values.

    Args:
        base_config_path: Path to an Oumi training config YAML.

    Returns:
        Dict mapping dot-notation field paths to (value, type_name) tuples.
    """
    from oumi.core.configs import TrainingConfig

    config = TrainingConfig.from_yaml(base_config_path)
    fields = {}

    def _extract(obj, prefix=""):
        for f in dataclasses.fields(obj):
            path = f"{prefix}{f.name}" if prefix else f.name
            val = getattr(obj, f.name)
            if dataclasses.is_dataclass(val) and not isinstance(val, type):
                _extract(val, f"{path}.")
            else:
                fields[path] = (val, type(val).__name__)

    _extract(config)
    return fields
'''


def write_workspace_helper(workspace_dir) -> str:
    """Write the oumi_helper.py file into the AIDE workspace.

    Args:
        workspace_dir: Path to the AIDE workspace directory (str or Path).

    Returns:
        The absolute path to the written helper file.
    """
    from pathlib import Path

    helper_path = Path(workspace_dir) / "oumi_helper.py"
    helper_path.write_text(OUMI_HELPER_SCRIPT)
    return str(helper_path)
