# Copyright 2025 - Oumi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Params for tool configuration in agentic synthesis."""

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ToolOutputStrategy(str, Enum):
    """Strategy for how a tool produces its output."""

    DETERMINISTIC = "deterministic"
    """Output is selected from user-defined values. One value is selected
    per conversation and reused for all calls to this tool within that
    conversation."""

    GENERATED = "generated"
    """Output is generated by an LLM simulator conditioned on the tool schema,
    arguments, conversation history, and optional environment state."""

    ENVIRONMENT = "environment"
    """Output comes from a stateful environment's step() method."""


@dataclass
class DeterministicToolOutput:
    """A possible canned output for a tool.

    Used with ToolOutputStrategy.DETERMINISTIC. One value is randomly selected
    per conversation, weighted by sample_rate. Matches the sampling pattern
    used by SampledAttributeValue in synthesis_params.
    """

    values: dict[str, Any] = field(default_factory=dict)
    """Structured output values. Serialized to JSON by the system at output time."""

    sample_rate: float | None = None
    """Selection weight. If not specified, assumes uniform sampling
    among all possible outputs. Must be between 0 and 1."""

    def __post_init__(self):
        """Verifies/populates params."""
        if not self.values:
            raise ValueError("DeterministicToolOutput.values cannot be empty.")
        if self.sample_rate is not None and (
            self.sample_rate < 0 or self.sample_rate > 1
        ):
            raise ValueError(
                "DeterministicToolOutput.sample_rate must be between 0 and 1."
            )


@dataclass
class GeneratedToolOutput:
    """Configuration for LLM-simulated tool output.

    Used with ToolOutputStrategy.GENERATED. The LLM simulator receives
    the tool definition, call arguments, conversation history, and this
    config to produce a realistic output.
    """

    instruction: str
    """Prompt hint for the LLM simulator. Guides what kind of output to produce.
    Example: "Return eligibility based on order status and 30-day return window."
    """

    def __post_init__(self):
        """Verifies/populates params."""
        if not self.instruction:
            raise ValueError("GeneratedToolOutput.instruction cannot be empty.")


@dataclass
class ToolEnvironmentAttribute:
    """Defines a stateful environment for tool synthesis.

    Environments are stateful containers that tools operate on.
    Each environment maintains a JSON state document that evolves
    as tools read from and write to it.
    """

    id: str
    """Unique identifier. Referenced by ToolAttribute.environment."""

    name: str
    """Display name (e.g. 'Filesystem', 'PropertyManagementSystem')."""

    description: str
    """What this environment represents. Used in LLM prompts for
    state generation and tool result generation."""

    system_prompt: str
    """Instructions for the LLM managing this environment's state.
    Included in all _generate_result and _update_state prompts."""

    state_schema: dict[str, Any] | None = None
    """JSON Schema the state must conform to. If None, auto-generated
    from bound tools at initialization time."""

    initial_state: dict[str, Any] | None = None
    """Starting state document. If None, auto-generated from schema.
    Validated against state_schema when both are provided."""

    def __post_init__(self):
        """Verifies/populates params."""
        if not self.id:
            raise ValueError("ToolEnvironmentAttribute.id cannot be empty.")
        if not self.name:
            raise ValueError("ToolEnvironmentAttribute.name cannot be empty.")
        if not self.description:
            raise ValueError("ToolEnvironmentAttribute.description cannot be empty.")
        if not self.system_prompt:
            raise ValueError("ToolEnvironmentAttribute.system_prompt cannot be empty.")


@dataclass
class ToolAttribute:
    """Defines a tool available for agentic synthesis.

    Tools are defined at the GeneralSynthesisParams level and referenced
    by id from MultiTurnAttribute.available_tools.

    The output_strategy field determines which output config is used:
    - DETERMINISTIC: uses deterministic_outputs (list, one sampled per conversation)
    - GENERATED: uses generated_output (singular config for LLM simulator)
    """

    id: str
    """Unique identifier for the tool. Referenced by available_tools."""

    name: str
    """Display name of the tool (e.g., "SearchOrders").
    Used in the tool catalog and output tool definitions."""

    description: str
    """What the tool does. Shown in the tool catalog, used in simulation
    prompts, and included in output tool definitions."""

    output_strategy: ToolOutputStrategy = ToolOutputStrategy.GENERATED
    """How this tool produces its output."""

    parameters: dict[str, Any] = field(default_factory=dict)
    """JSON Schema for tool parameters. Matches the OpenAI/HuggingFace standard.

    Example::

        {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "string",
                    "description": "The customer's ID"
                }
            },
            "required": ["customer_id"]
        }
    """

    output_schema: dict[str, Any] = field(default_factory=dict)
    """JSON Schema describing the tool's output structure. Shared across strategies.

    For DETERMINISTIC: used to validate that canned outputs conform to the schema.
    For GENERATED: passed to the LLM simulator as structure guidance.

    Example::

        {
            "type": "object",
            "properties": {
                "eligible": {"type": "boolean"},
                "reason": {"type": "string"}
            }
        }
    """

    deterministic_outputs: list[DeterministicToolOutput] = field(default_factory=list)
    """Possible canned outputs for DETERMINISTIC strategy.

    One is selected per conversation, weighted by sample_rate (uniform if unset).
    Selection happens once at conversation initialization, not per-call."""

    generated_output: GeneratedToolOutput | None = None
    """Configuration for LLM-simulated output for GENERATED strategy.

    The LLM simulator uses this config along with the tool call arguments
    and conversation context to produce a realistic output."""

    environment: str | None = None
    """References an ToolEnvironmentAttribute.id. When set, output_strategy
    must be ENVIRONMENT and tool results come from env.step()."""

    read_only: bool = True
    """Whether this tool modifiesits environment's state.
    Only relevant when environment is set."""

    def __post_init__(self):
        """Verifies/populates params."""
        if not self.id:
            raise ValueError("ToolAttribute.id cannot be empty.")
        if not self.name:
            raise ValueError("ToolAttribute.name cannot be empty.")
        if not self.description:
            raise ValueError("ToolAttribute.description cannot be empty.")
        if self.output_strategy == ToolOutputStrategy.ENVIRONMENT:
            if not self.environment:
                raise ValueError(
                    "ToolAttribute.environment must be set "
                    "when output_strategy is ENVIRONMENT."
                )
            return

        if self.environment:
            raise ValueError(
                "ToolAttribute.output_strategy must be ENVIRONMENT "
                "when environment is set."
            )

        if self.output_strategy == ToolOutputStrategy.DETERMINISTIC:
            if not self.deterministic_outputs:
                raise ValueError(
                    "ToolAttribute.deterministic_outputs cannot be empty "
                    "when output_strategy is DETERMINISTIC."
                )
            self._normalize_sample_rates()

        elif self.output_strategy == ToolOutputStrategy.GENERATED:
            if not self.generated_output:
                raise ValueError(
                    "ToolAttribute.generated_output must be provided "
                    "when output_strategy is GENERATED."
                )

    def _normalize_sample_rates(self) -> None:
        """Normalize sample rates for deterministic outputs.

        Matches the pattern used by SampledAttribute for consistency:
        - Defined rates are summed
        - Remaining probability is split uniformly among undefined rates
        """
        sample_rates = [o.sample_rate for o in self.deterministic_outputs]

        defined_rate = 0.0
        undefined_count = 0
        for rate in sample_rates:
            if rate is not None:
                defined_rate += rate
            else:
                undefined_count += 1

        if defined_rate > 1.0 and not math.isclose(defined_rate, 1.0):
            raise ValueError(
                "ToolAttribute.deterministic_outputs sample rates "
                "must sum to at most 1.0."
            )

        if undefined_count > 0:
            remaining = max(0.0, 1.0 - defined_rate)
            per_undefined = remaining / undefined_count
            for output_value in self.deterministic_outputs:
                if output_value.sample_rate is None:
                    output_value.sample_rate = per_undefined
