# Copyright 2025 - Oumi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Params for tool configuration in agentic synthesis."""

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ToolOutputStrategy(str, Enum):
    """Strategy for how a tool produces its output."""

    DETERMINISTIC = "deterministic"
    """Output is selected from user-defined values. One value is selected
    per conversation and reused for all calls to this tool within that
    conversation."""

    GENERATED = "generated"
    """Output is generated by an LLM simulator conditioned on the tool schema,
    arguments, conversation history, and optional environment state."""


@dataclass
class ToolOutputValue:
    """A possible deterministic output for a tool.

    Used with ToolOutputStrategy.DETERMINISTIC. One value is randomly selected
    per conversation, weighted by sample_rate.
    """

    output: str
    """The tool output as a JSON string."""

    sample_rate: float | None = None
    """Selection weight. If not specified, assumes uniform sampling
    among all possible outputs."""

    def __post_init__(self):
        """Verifies/populates params."""
        if not self.output:
            raise ValueError("ToolOutputValue.output cannot be empty.")
        if self.sample_rate is not None and (
            self.sample_rate < 0 or self.sample_rate > 1
        ):
            raise ValueError("ToolOutputValue.sample_rate must be between 0 and 1.")


@dataclass
class ToolAttribute:
    """Defines a tool available for agentic synthesis.

    Tools are defined at the GeneralSynthesisParams level and referenced
    by id from MultiTurnAttribute.available_tools.

    The output_strategy field determines which other fields are relevant:
    - DETERMINISTIC: uses deterministic_outputs
    - GENERATED: uses output_instruction and/or output_schema
    """

    id: str
    """Unique identifier for the tool. Referenced by available_tools."""

    name: str
    """Display name of the tool (e.g., "SearchOrders")."""

    description: str
    """What the tool does. Shown to the planner and used in simulation prompts."""

    output_strategy: ToolOutputStrategy = ToolOutputStrategy.GENERATED
    """How this tool produces its output."""

    parameters: dict[str, Any] = field(default_factory=dict)
    """Parameter schema. Keys are parameter names, values describe the parameter.
    Example: {"customer_id": {"type": "string", "required": true}}"""

    # DETERMINISTIC fields
    deterministic_outputs: list[ToolOutputValue] = field(default_factory=list)
    """Possible outputs for DETERMINISTIC mode. One is selected per conversation,
    weighted by sample_rate (uniform if unset)."""

    # GENERATED fields
    output_instruction: str = ""
    """Prompt hint for the LLM simulator. Guides what kind of output to produce."""

    output_schema: dict[str, Any] = field(default_factory=dict)
    """Expected output structure for the LLM simulator to follow.
    Example: {"eligible": {"type": "boolean"}, "reason": {"type": "string"}}"""

    # Optional environment interaction
    mutates_environment: bool = False
    """Whether this tool updates environment state. Only relevant when an
    environment is defined on the MultiTurnAttribute. Ignored otherwise."""

    def __post_init__(self):
        """Verifies/populates params."""
        if not self.id:
            raise ValueError("ToolAttribute.id cannot be empty.")
        if not self.name:
            raise ValueError("ToolAttribute.name cannot be empty.")
        if not self.description:
            raise ValueError("ToolAttribute.description cannot be empty.")

        if self.output_strategy == ToolOutputStrategy.DETERMINISTIC:
            if not self.deterministic_outputs:
                raise ValueError(
                    "ToolAttribute.deterministic_outputs cannot be empty "
                    "when output_strategy is DETERMINISTIC."
                )
            self._normalize_sample_rates()

        elif self.output_strategy == ToolOutputStrategy.GENERATED:
            if not self.output_instruction and not self.output_schema:
                raise ValueError(
                    "ToolAttribute must have at least one of "
                    "output_instruction or output_schema "
                    "when output_strategy is GENERATED."
                )

    def _normalize_sample_rates(self) -> None:
        """Normalize sample rates for deterministic outputs.

        Matches the pattern used by SampledAttribute for consistency.
        """
        sample_rates = [o.sample_rate for o in self.deterministic_outputs]

        defined_rate = 0.0
        undefined_count = 0
        for rate in sample_rates:
            if rate is not None:
                defined_rate += rate
            else:
                undefined_count += 1

        if defined_rate > 1.0 and not math.isclose(defined_rate, 1.0):
            raise ValueError(
                "ToolAttribute.deterministic_outputs sample rates "
                "must sum to at most 1.0."
            )

        if undefined_count > 0:
            remaining = max(0.0, 1.0 - defined_rate)
            per_undefined = remaining / undefined_count
            for output_value in self.deterministic_outputs:
                if output_value.sample_rate is None:
                    output_value.sample_rate = per_undefined


@dataclass
class EnvironmentConfig:
    """Optional environment configuration for stateful tool interactions.

    When defined on a MultiTurnAttribute, tools can read from and write to
    a shared mutable state. Both fields support {placeholder} resolution
    from sampled/generated attributes.

    When not defined, tools operate statelessly.
    """

    entities: dict[str, Any] = field(default_factory=dict)
    """Structured state template with {placeholders}.
    Example: {"orders": {"{order_id}": {"status": "{order_status}"}}}"""

    context: str = ""
    """Domain rules/constraints template with {placeholders}.
    Example: "{return_policy}"."""

    def __post_init__(self):
        """Verifies/populates params."""
        if not self.entities and not self.context:
            raise ValueError(
                "EnvironmentConfig must have at least one of entities or context."
            )
