# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversation.proto
# Protobuf Python Version: 5.27.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 5, "", "conversation.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x63onversation.proto\x12\x17oumi.core.conversations"2\n\x08\x44\x61taBlob\x12\x11\n\tmime_type\x18\x01 \x01(\t\x12\x13\n\x0b\x62inary_data\x18\x02 \x01(\x0c"\xed\x01\n\x0b\x43ontentItem\x12\x37\n\x04type\x18\x01 \x01(\x0e\x32).oumi.core.conversations.ContentItem.Type\x12\x11\n\x07\x63ontent\x18\x02 \x01(\tH\x00\x12\x31\n\x04\x62lob\x18\x03 \x01(\x0b\x32!.oumi.core.conversations.DataBlobH\x00"W\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04TEXT\x10\x01\x12\x0e\n\nIMAGE_PATH\x10\x02\x12\r\n\tIMAGE_URL\x10\x03\x12\x10\n\x0cIMAGE_BINARY\x10\x04\x42\x06\n\x04\x64\x61tab\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "conversation_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DATABLOB"]._serialized_start = 47
    _globals["_DATABLOB"]._serialized_end = 97
    _globals["_CONTENTITEM"]._serialized_start = 100
    _globals["_CONTENTITEM"]._serialized_end = 337
    _globals["_CONTENTITEM_TYPE"]._serialized_start = 242
    _globals["_CONTENTITEM_TYPE"]._serialized_end = 329
# @@protoc_insertion_point(module_scope)
